{
    "children": null,
    "attachments": null,
    "relations": null,
    "changesets": [],
    "journals": [
        {
            "id": 7385,
            "user": {
                "id": 3,
                "name": "IR4T4"
            },
            "notes": "@Ray how did you connect? From another mod, from server browser, +connect etlegacy.com ?",
            "created_on": "2018-12-23T23:58:07Z",
            "details": []
        },
        {
            "id": 7387,
            "user": {
                "id": 596,
                "name": "Ray"
            },
            "notes": "IR4T4 wrote:\r\n> @Ray how did you connect? From another mod, from server browser, +connect etlegacy.com ?\r\n\r\n@IR4T4\r\n I connected thru console:  /connect etlegacy.com\r\n\r\n",
            "created_on": "2018-12-24T08:12:20Z",
            "details": []
        },
        {
            "id": 7476,
            "user": {
                "id": 140,
                "name": "Spyhawk"
            },
            "notes": "This seems to happen very rarely. We'll need more feedback or a way to reproduce. At first sight, this looks like some packets were lost on the way.",
            "created_on": "2018-12-31T15:53:23Z",
            "details": [
                {
                    "property": "attr",
                    "name": "priority_id",
                    "old_value": "6",
                    "new_value": "3"
                },
                {
                    "property": "attr",
                    "name": "fixed_version_id",
                    "old_value": "19",
                    "new_value": "8"
                }
            ]
        },
        {
            "id": 7504,
            "user": {
                "id": 3,
                "name": "IR4T4"
            },
            "notes": "",
            "created_on": "2019-01-06T08:17:22Z",
            "details": [
                {
                    "property": "attr",
                    "name": "fixed_version_id",
                    "old_value": "8",
                    "new_value": "22"
                }
            ]
        },
        {
            "id": 7674,
            "user": {
                "id": 3,
                "name": "IR4T4"
            },
            "notes": "",
            "created_on": "2019-01-24T13:17:30Z",
            "details": [
                {
                    "property": "attr",
                    "name": "fixed_version_id",
                    "old_value": "22",
                    "new_value": "8"
                }
            ]
        },
        {
            "id": 7840,
            "user": {
                "id": 256,
                "name": "keMoN"
            },
            "notes": "Copy-paste from a friendly server admin:\r\n\"Any idea what would cause a constant stream of \"WARNING: bad command byte for client 4\" errors in the server console to the point where the clients cannot move and is lagged out, then they get disconnected with the message \"cl_parseservermessage: Illegible server message 224\", if they try to reconnect immediately they get kicked and a temp ban.\r\n\r\nWe had this yesterday for lots of clients, I thought it was because we had exceeded the amount of maps as we had uploaded new maps prior to this, once I deleted some maps the issue did not happen again all night but it has begun again today.\"",
            "created_on": "2019-03-05T16:19:23Z",
            "details": [
                {
                    "property": "attr",
                    "name": "priority_id",
                    "old_value": "3",
                    "new_value": "5"
                },
                {
                    "property": "attr",
                    "name": "fixed_version_id",
                    "old_value": "8",
                    "new_value": "22"
                }
            ]
        },
        {
            "id": 7842,
            "user": {
                "id": 256,
                "name": "keMoN"
            },
            "notes": "Kimi|AHK said in TM Discord that they received this error while playing with a vanilla ET client.",
            "created_on": "2019-03-06T17:18:46Z",
            "details": []
        },
        {
            "id": 7843,
            "user": {
                "id": 421,
                "name": "kimi"
            },
            "notes": "ye after that i switch to legacy client and didnt have problem",
            "created_on": "2019-03-06T22:41:16Z",
            "details": []
        },
        {
            "id": 8365,
            "user": {
                "id": 140,
                "name": "Spyhawk"
            },
            "notes": "",
            "created_on": "2019-07-08T10:33:27Z",
            "details": [
                {
                    "property": "attr",
                    "name": "fixed_version_id",
                    "old_value": "22",
                    "new_value": "8"
                }
            ]
        }
    ],
    "watchers": [
        {
            "id": 421,
            "name": "kimi"
        }
    ],
    "time_entries": null,
    "id": 1135,
    "project": {
        "id": 1,
        "name": "ET: Legacy Development"
    },
    "tracker": {
        "id": 1,
        "name": "Bug"
    },
    "status": {
        "id": 1,
        "name": "New"
    },
    "priority": {
        "id": 5,
        "name": "High"
    },
    "author": {
        "id": 140,
        "name": "Spyhawk"
    },
    "category": {
        "id": 1,
        "name": "Client"
    },
    "fixed_version": {
        "id": 8,
        "name": "2.78"
    },
    "subject": "CL_ParseServerMessage crash",
    "description": "Ray:\r\ncrashed\r\n\r\nError message: \"Illegible Server message 69\"\r\n",
    "start_date": "2018-12-22",
    "done_ratio": 0,
    "custom_fields": [
        {
            "id": 1,
            "name": "OS",
            "value": ""
        },
        {
            "id": 2,
            "name": "Arch",
            "value": ""
        }
    ],
    "created_on": "2018-12-22T21:21:57Z",
    "updated_on": "2019-07-08T10:33:27Z"
}